name: TradeE
version: 0.6
api-version: 1.17
main: de.mrg4ming.Main
author: MrG4ming
description: A plugin for money management and a trade system.

commands:
  trade:
    description: Manage Trades.
    usage: §8[§bTradeE§8]§6 /trade <create|remove|constant> <tradeName> <bankAccountOwner>
  bank:
    description: Manage your bank account.
    usage: §8[§bTradeE§8]§6 /bank <create|close|transfer|info> <accountName> [amount] [targetAccountName]
    permission: tradee.bank.*
    permission-message: §8[§bTradeE§8]§6 §4You don's have the permission to use this command!
  reloadconfig:
    description: Reloads all the configuration files.
    usage: §8[§bTradeE§8]§6 /reloadconfig

permissions:
   tradee.config:
      description: Permission to reload TradeE config.
   tradee.trade.spawn:
      description: TradeE trading villager spawn permission.
      default: op
   tradee.trade.user:
      description: TradeE trading user permission.
      default: true
   tradee.trade.manager:
      description: TradeE trading manager permission.
      default: op
   tradee.bank.manager:
      description: TradeE bank create or close permission.
      default: op
   tradee.bank.user:
      description: TradeE bank user permissions.
      default: true
   tradee.bank.*:
    description: TradeE bank command permissions.
    default: true
